In [9]:
# Practical no . 5

In [1]:
#Name : Sujal P Gulhane
#Roll No: 71
#Sec : A

In [ ]:
#Aim : Creation of Array Using Numpy

In [2]:
import random

In [13]:
rm =[random.randint(1,50) for _ in range(15)]

In [14]:
rm

[49, 30, 43, 12, 37, 28, 13, 36, 9, 21, 39, 32, 42, 41, 46]

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# 1-D Array

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
# 2-D Array

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
